// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"encoding/json"
	"time"
)

type Banner struct {
	ID        int32
	FeatureID int32
	IsActive  bool
	Content   json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

type BannerRelation struct {
	BannerID  int32
	FeatureID int32
	TagID     int32
}
