// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"encoding/json"
	"time"
)

type Banner struct {
	Feature     int32
	Tag         int32
	JsonContent json.RawMessage
	IsActive    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
